src/checkout/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from checkout import settings

urlpatterns = [
    path(
        "robots.txt",
        TemplateView.as_view(
            template_name="common/robots.txt",
            content_type="text/plain",
        ),
    ),
    path("", include("common.urls")),
    path("admin/", admin.site.urls),
    path("purchase/", include("purchase.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/common/urls.py
from django.urls import path

from common import views

app_name = "common"
urlpatterns = [
    path("error_check/", views.error_check, name="error_check"),
    path("ping/", views.ping, name="ping"),
    path("", views.home, name="home"),
]

src/purchase/urls.py
from django.urls import path

from purchase.views import (
    additional_unpriced_product,
    delete_basket,
    list_baskets,
    new_basket,
    price_preview,
    update_basket,
)
from purchase.views.reports import by_hour_plot_view, products_plots_view, reports

app_name = "purchase"
urlpatterns = [
    path("", list_baskets, name="list"),
    path("price_preview/", price_preview, name="price_preview"),
    path("new/", new_basket, name="new"),
    path("<int:pk>/update/", update_basket, name="update"),
    path("<int:pk>/delete/", delete_basket, name="delete"),
    path(
        "additional_unpriced_product/",
        additional_unpriced_product,
        name="additional_unpriced_product",
    ),
    path("reports/", reports, name="reports"),
    # plots
    path("reports/products_plots/", products_plots_view, name="products_plots"),
    path("reports/by_hour_plot/", by_hour_plot_view, name="by_hour_plot"),
]

src/purchase/models.py
from __future__ import annotations

import uuid

from django.core.validators import MaxValueValidator
from django.db import models
from django.db.models import Avg, Count, F, Sum
from django.db.models.functions import Coalesce
from django.urls import reverse
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _
from solo.models import SingletonModel


class Model(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created at"))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("updated at"))

    class Meta:
        abstract = True


class PaymentMethodQuerySet(models.QuerySet):
    def with_turnover(self):
        return self.annotate(
            turnover=Coalesce(
                Sum(
                    F("baskets__items__quantity")
                    * F("baskets__items__unit_price_cents"),
                ),
                0,
            ),
        )

    def with_sold(self):
        return self.annotate(sold=Count("baskets", distinct=True))


class PaymentMethodManager(models.Manager):
    def get_by_natural_key(self, name):
        return self.get(name=name)


class PaymentMethod(Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=_("name"))

    objects = PaymentMethodManager.from_queryset(PaymentMethodQuerySet)()

    class Meta:
        verbose_name = _("payment method")
        verbose_name_plural = _("payment methods")
        ordering = ("name",)

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.name,)


def default_product_display_order():
    last = Product.objects.last()
    if last is None:
        return 1
    return last.display_order + 1


class ProductCategory(Model):
    name = models.CharField(max_length=250, unique=True, verbose_name=_("name"))
    color_hue = models.PositiveIntegerField(
        validators=[MaxValueValidator(360)],
        verbose_name=_("color hue"),
        help_text=_("Color hue in degrees (0-360)"),
    )

    class Meta:
        verbose_name = _("product category")
        verbose_name_plural = _("product categories")

    def __str__(self):
        return self.name


class ProductQuerySet(models.QuerySet):
    def with_turnover(self):
        return self.annotate(
            turnover=Coalesce(
                Sum(F("basket_items__quantity") * F("basket_items__unit_price_cents")),
                0,
            ),
        )

    def with_sold(self):
        return self.annotate(sold=Coalesce(Sum("basket_items__quantity"), 0))

    def with_fixed_price(self):
        return self.exclude(unit_price_cents=0)

    def with_no_fixed_price(self):
        return self.filter(unit_price_cents=0)

    def with_category(self):
        return self.select_related("category")


class ProductManager(models.Manager):
    def get_by_natural_key(self, name):
        return self.get(name=name)


class Product(Model):
    name = models.CharField(max_length=250, unique=True, verbose_name=_("name"))
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.PROTECT,
        verbose_name=_("category"),
        null=False,
        blank=False,
    )
    unit_price_cents = models.PositiveIntegerField(
        verbose_name=_("unit price (cents)"),
        help_text=_(
            "Unit price in cents. Use zero to denote that the product has no fixed price.",
        ),
    )
    initials = models.CharField(
        max_length=10,
        verbose_name=_("initials"),
        blank=False,
        null=False,
    )
    display_order = models.PositiveIntegerField(
        default=default_product_display_order,
        verbose_name=_("display order"),
    )

    objects = ProductManager.from_queryset(ProductQuerySet)()

    class Meta:
        ordering = ["display_order", "name"]
        verbose_name = _("product")
        verbose_name_plural = _("products")

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.name,)

    @property
    def color_hue(self):
        return self.category.color_hue

    @property
    def has_fixed_price(self) -> bool:
        return self.unit_price_cents > 0


class BasketQuerySet(models.QuerySet):
    def with_articles_count(self) -> BasketQuerySet:
        return self.annotate(articles_count=Sum(F("items__quantity")))

    def priced(self) -> BasketQuerySet:
        return self.annotate(
            price=Coalesce(Sum(F("items__quantity") * F("items__unit_price_cents")), 0),
        )

    def average_basket(self) -> float:
        return self.priced().aggregate(avg=Avg("price"))["avg"]

    def by_date(self, date) -> BasketQuerySet:
        return self.filter(created_at__date=date)

    def turnover(self) -> int:
        return self.priced().aggregate(total=Sum("price"))["total"]


class Basket(Model):
    payment_method = models.ForeignKey(
        to=PaymentMethod,
        on_delete=models.PROTECT,
        related_name="baskets",
        null=False,
        blank=False,
        verbose_name=_("payment method"),
    )

    objects = BasketQuerySet.as_manager()

    class Meta:
        verbose_name = _("basket")
        verbose_name_plural = _("baskets")

    def __str__(self):
        return gettext("Basket #%(id)s") % {"id": self.id}

    def get_absolute_url(self):
        return reverse("purchase:update", args=(self.pk,))


class BasketItemQuerySet(models.QuerySet):
    def priced(self):
        return self.annotate(price=Coalesce(F("quantity") * F("unit_price_cents"), 0))


class BasketItem(Model):  # noqa: DJ008
    product = models.ForeignKey(
        to=Product,
        on_delete=models.PROTECT,
        related_name="basket_items",
        verbose_name=_("product"),
    )
    basket = models.ForeignKey(
        to=Basket,
        on_delete=models.CASCADE,
        related_name="items",
        verbose_name=_("basket"),
    )
    quantity = models.PositiveIntegerField(verbose_name=_("quantity"))
    unit_price_cents = models.PositiveIntegerField(
        verbose_name=_("unit price (cents)"),
        help_text=_("product's unit price in cents at the time of purchase"),
    )

    objects = BasketItemQuerySet.as_manager()

    class Meta:
        verbose_name = _("basket item")
        verbose_name_plural = _("basket items")


class Cache(SingletonModel):
    etag = models.UUIDField(default=uuid.uuid4)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return str(self.etag)

    def refresh(self):
        self.etag = uuid.uuid4()
        self.save()


def reports_etag(_request):
    return str(Cache.get_solo().etag)


def reports_last_modified(_request):
    return Cache.get_solo().last_modified

src/purchase/forms.py
from crispy_forms import layout
from crispy_forms.bootstrap import InlineRadios
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Layout, Submit
from django import forms
from django.urls import reverse
from django.utils.translation import gettext as _

from purchase.layout import BasketItemField
from purchase.models import Basket, Product

PRICED_PREFIX = "product-"
UNPRICED_PREFIX = "unpriced_product-"


class BasketForm(forms.ModelForm):
    class Meta:
        model = Basket
        fields = ["payment_method"]
        widgets = {"payment_method": forms.RadioSelect}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "form-horizontal"
        self.helper.add_input(Submit("submit", _("Save")))
        self.helper.attrs = {
            "hx_post": reverse("purchase:price_preview"),
            "hx_trigger": "keyup delay:500ms,change delay:500ms",
            "hx_target": "#price_preview",
            "hx_swap": "innerHTML",
        }
        self.helper.layout = Layout()
        products = {}
        basket = kwargs.get("instance")
        if basket:
            for item in basket.items.all():
                products[item.product] = item.quantity
        fields = []
        for product in Product.objects.with_category().with_fixed_price():
            field_name = f"{PRICED_PREFIX}{product.id}"
            self.fields.update(
                {
                    field_name: forms.IntegerField(
                        label=product.name,
                        min_value=0,
                        initial=products.get(product, 0),
                    ),
                },
            )
            fields.append(BasketItemField(field_name, product=product))
        total = 0
        count = 0
        if basket:
            total = basket.price / 100
            count = basket.articles_count
        self.helper.layout = Layout(
            Div(
                *fields,
                css_class="row row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-lg-5 row-cols-xl-6 g-4",
                css_id="products",
            ),
            InlineRadios("payment_method"),
            Div(
                layout.HTML(
                    f"Montant total : {total:.2f}€<br>Nombre d'articles: {count}",
                ),
                css_id="price_preview",
                css_class="mb-2",
            ),
        )

    def save(self):
        instance: Basket = super().save(commit=True)
        name: str
        products = {product.id: product for product in Product.objects.all()}
        for name, value in self.cleaned_data.items():
            if name.startswith(PRICED_PREFIX):
                product_id = int(name.removeprefix(PRICED_PREFIX))
                product = products[product_id]
                if value > 0:
                    instance.items.update_or_create(
                        product=product,
                        defaults={
                            "quantity": value,
                            "unit_price_cents": product.unit_price_cents,
                        },
                    )
                if value == 0:
                    instance.items.filter(product=product).delete()
        return instance

src/purchase/views/basket.py
import logging

from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.datastructures import MultiValueDict
from django.utils.translation import gettext_lazy as _
from django.views.decorators.http import condition, require_http_methods
from django_htmx.http import trigger_client_event

from purchase.forms import PRICED_PREFIX, UNPRICED_PREFIX, BasketForm
from purchase.models import Basket, Product, reports_etag, reports_last_modified

logger = logging.getLogger(__name__)


@require_http_methods(["GET", "POST"])
@permission_required("purchase.add_basket")
def new_basket(request: WSGIRequest) -> HttpResponse:
    if request.method == "POST":
        form = BasketForm(request.POST)
        if form.is_valid():
            basket = form.save()
            update_with_unpriced_products(basket, request.POST)
            if request.user.has_perm("purchase.change_basket"):
                url = basket.get_absolute_url()
            else:
                url = reverse("purchase:new")
            messages.success(request, _("Successfully created basket."))
            return redirect(url)
    else:
        form = BasketForm()

    return render(
        request,
        "purchase/basket_form.html",
        {"form": form, "products": Product.objects.with_no_fixed_price()},
    )


def update_with_unpriced_products(basket: Basket, post_data: MultiValueDict):
    no_fixed_price = {
        product.id: product for product in Product.objects.with_no_fixed_price()
    }
    basket.items.filter(product__in=no_fixed_price.values()).delete()
    for product_id, product in no_fixed_price.items():
        if prices := post_data.getlist(f"{UNPRICED_PREFIX}{product_id}"):
            for price in map(int, prices):
                if price:
                    basket.items.create(
                        product=product,
                        quantity=1,
                        unit_price_cents=price,
                    )


@require_http_methods(["GET", "POST"])
@permission_required("purchase.change_basket")
def update_basket(request: WSGIRequest, pk: int) -> HttpResponse:
    basket = get_object_or_404(Basket.objects.priced().with_articles_count(), pk=pk)
    if request.method == "POST":
        form = BasketForm(request.POST, instance=basket)
        if form.is_valid():
            basket = form.save()
            update_with_unpriced_products(basket, request.POST)
            messages.success(request, _("Successfully updated basket."))
            return redirect(basket.get_absolute_url())
    else:
        form = BasketForm(instance=basket)

    response = render(
        request,
        "purchase/basket_form.html",
        {
            "form": form,
            "basket": basket,
            "products": Product.objects.with_no_fixed_price(),
        },
    )
    trigger_client_event(response, "load-unpriced", after="swap")
    return response


@require_http_methods(["GET"])
def additional_unpriced_product(request: WSGIRequest) -> HttpResponse:
    product_id = request.GET.get("product_to_add")
    value = request.GET.get("value", 0)
    product = get_object_or_404(Product.objects.with_no_fixed_price(), pk=product_id)
    context = {"product": product, "value": value}
    res = render(
        request,
        "purchase/snippets/basket_unpriced_item.html",
        context,
    )
    return trigger_client_event(res, "newUnpriced", after="settle")


@permission_required("purchase.view_basket")
@condition(etag_func=reports_etag, last_modified_func=reports_last_modified)
def list_baskets(request: WSGIRequest) -> HttpResponse:
    context = {"baskets": Basket.objects.with_articles_count().priced().order_by("-id")}
    return render(request, "purchase/basket_list.html", context)


@require_http_methods(["GET", "POST"])
@permission_required("purchase.delete_basket")
def delete_basket(request: WSGIRequest, pk: int) -> HttpResponse:
    basket = get_object_or_404(Basket, pk=pk)
    if request.method == "GET":
        context = {"basket": basket}
        return render(request, "purchase/basket_confirm_delete.html", context)
    basket.delete()
    messages.success(request, _("Basket successfully deleted."))
    return redirect("purchase:list")


@require_http_methods(["POST"])
@permission_required("purchase.add_basket")
def price_preview(request: WSGIRequest) -> HttpResponse:
    total = 0
    count = 0
    for name in request.POST:
        if name.startswith(PRICED_PREFIX):
            product_id = name[len(PRICED_PREFIX) :]
            product = get_object_or_404(Product, pk=product_id)
            number = int(request.POST.get(name, 0))
            total += product.unit_price_cents * number
            count += number
        elif name.startswith(UNPRICED_PREFIX):
            prices = list(filter(lambda x: x > 0, map(int, request.POST.getlist(name))))
            total += sum(prices)
            count += len(prices)

    total = f"{total/100:.2f}€"
    return HttpResponse(
        f'<span hx-swap-oob="true" id="basket-price" class="badge bg-secondary">{total}</span>Montant total : {total}<br>Nombre d\'articles: {count}',
    )

src/purchase/templates/purchase/basket_confirm_delete.html
{% extends "common/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{{ object }}</h1>
    <form method="post">
        {% csrf_token %}
        <p>{% blocktranslate %}Are you sure you want to delete "{{ basket }}"?{% endblocktranslate %}</p>
        <input class="btn btn-danger" type="submit" value="Confirm">
    </form>
{% endblock %}

src/purchase/templates/purchase/basket_form.html
{% extends "common/base.html" %}
{% load i18n static crispy_forms_tags purchase django_htmx %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static "purchase/css/basket_form.css" %}">
{% endblock %}
{% block content %}
    {% if basket %}
        <h1>{{ basket }} <span id="basket-price" class="badge bg-secondary">{{ basket.price|currency }}</span></h1>
        <p class="metadata">
            {{ basket.created_at }}
        </p>
        {% if not basket.payment_method %}
            <div class="alert alert-danger" role="alert">{% translate "Missing payment method." %}</div>
        {% endif %}
    {% else %}
        <h1>{% translate "New basket" %} <span id="basket-price" class="badge bg-secondary d-none">{{ basket.price|currency }}</span></h1>
    {% endif %}
    {% crispy form %}
    <div class="row">
        <div class="col">
            <form
                hx-get="{% url "purchase:additional_unpriced_product" %}"
                hx-target="#products"
                hx-swap="beforeend"
            >
                <div class="input-group">
                    <select class="form-select" name="product_to_add" id="product_to_add">
                        {% for product in products %}
                            <option value="{{ product.pk }}">{{ product.name }}</option>
                        {% endfor %}
                    </select>
                    <button
                        class="btn btn-outline-secondary"
                        type="submit"
                        id="add_product"
                    >
                        {% translate "Add product" %}
                    </button>
                </div>
            </form>
        </div>
    </div>
    {% for item in basket.items.all %}
        {% if item.product.unit_price_cents == 0 %}
            <input
                type="hidden"
                hx-get="{% url "purchase:additional_unpriced_product" %}?product_to_add={{ item.product.pk }}&value={{ item.unit_price_cents }}"
                hx-trigger="load"
                hx-target="#products"
                hx-swap="beforeend"
            >
        {% endif %}
    {% endfor %}
    <div class="row mt-4">
        <div class="col">
            {% if basket %}
                <a href="{% url "purchase:new" %}" class="btn btn-secondary">{% translate "New basket" %}</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block extrascript %}
    <script src="{% static 'vendor/htmx-1.8.6/htmx.min.js' %}" defer></script>
    {% django_htmx_script %}
    <script defer type="application/javascript" src="{% static "purchase/js/basket_form.js" %}"></script>
{% endblock %}

src/purchase/templates/purchase/basket_list.html
{% extends "common/base.html" %}
{% load i18n %}
{% load purchase %}
{% block content %}
    <h1>{% translate "Baskets" %}</h1>
    <div class="row row-cols-2 row-cols-xl-6 row-cols-lg-5 row-cols-md-4 row-cols-sm-3 g-4">
        {% for basket in baskets %}
            <div class="col">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">{% blocktranslate with basket_id=basket.id %}Basket #{{ basket_id }}{% endblocktranslate %}</h5>
                        <p class="card-text">
                            {% blocktranslate count counter=basket.articles_count %}1 item{% plural %}{{ counter }} items{% endblocktranslate %}<br>
                            {{ basket.price|currency }}<br>
                            {{ basket.payment_method|default:"-" }}<br>
                            {% now "Y-m-d" as todays_date %}
                            {% if basket.created_at|date:"Y-m-d" == todays_date %}
                                {{ basket.created_at|date:"TIME_FORMAT" }}
                            {% else %}
                                {{ basket.created_at }}
                            {% endif %}
                        </p>
                        <div class="btn-group btn-group-sm">
                            {% if perms.purchase.change_basket %}
                                <a href="{% url "purchase:update" basket.id %}" class="btn btn-primary"><i class="fa-solid fa-pen-to-square"></i></a>
                            {% endif %}
                            {% if perms.purchase.delete_basket %}
                                <a href="{% url "purchase:delete" basket.id %}" class="btn btn-danger"><i class="fa-solid fa-trash"></i></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

src/purchase/templates/purchase/reports.html
{% extends "common/base.html" %}
{% load static i18n purchase django_htmx %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static "purchase/css/reports.css" %}">
{% endblock %}

{% block content %}
    <h1>{% translate "Reports" %}</h1>
    <h2>{% translate "All times" %}</h2>
    <ul>
        <li>{% translate "Total turnover:" %} {{ turnover|currency }}</li>
        <li>{% translate "Average basket:" %} {{ average_basket|currency }}</li>
        <li>{% translate "Number of baskets:" %} {{ basket_count }}</li>
    </ul>

    <h3>{% translate "By day" %}</h3>
    {% include "purchase/snippets/by_day_table.html" %}

    {% if date %}
        <h3>{% translate "By hour" %} <small class="text-muted">{{ date }}</small></h3>
        {% include "purchase/snippets/htmx_plot.html" with url='purchase:by_hour_plot' %}
    {% endif %}

    <h2>{% translate "Products" %} <small class="text-muted">{{ date }}</small></h2>
    {% include "purchase/snippets/report_products.html" %}
    {% include "purchase/snippets/htmx_plot.html" with url='purchase:products_plots' %}

    <h2>{% translate "Turnover by payment method" %} <small class="text-muted">{{ date }}</small></h2>
    {% include "purchase/snippets/report_payment_methods.html" %}

{% endblock %}

{% block extrascript %}
    <script src="{% static 'vendor/htmx-1.8.6/htmx.min.js' %}" defer></script>
    {% django_htmx_script %}
{% endblock %}