src/checkout/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from checkout import settings

urlpatterns = [
    path(
        "robots.txt",
        TemplateView.as_view(
            template_name="common/robots.txt",
            content_type="text/plain",
        ),
    ),
    path("", include("common.urls")),
    path("admin/", admin.site.urls),
    path("purchase/", include("purchase.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/common/urls.py
from django.urls import path

from common import views

app_name = "common"
urlpatterns = [
    path("error_check/", views.error_check, name="error_check"),
    path("ping/", views.ping, name="ping"),
    path("", views.home, name="home"),
]

src/purchase/urls.py
from django.urls import path

from purchase.views import (
    additional_unpriced_product,
    delete_basket,
    list_baskets,
    new_basket,
    price_preview,
    update_basket,
)
from purchase.views.reports import by_hour_plot_view, products_plots_view, reports

app_name = "purchase"
urlpatterns = [
    path("", list_baskets, name="list"),
    path("price_preview/", price_preview, name="price_preview"),
    path("new/", new_basket, name="new"),
    path("<int:pk>/update/", update_basket, name="update"),
    path("<int:pk>/delete/", delete_basket, name="delete"),
    path(
        "additional_unpriced_product/",
        additional_unpriced_product,
        name="additional_unpriced_product",
    ),
    path("reports/", reports, name="reports"),
    # plots
    path("reports/products_plots/", products_plots_view, name="products_plots"),
    path("reports/by_hour_plot/", by_hour_plot_view, name="by_hour_plot"),
]

src/common/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

src/purchase/models.py
from __future__ import annotations

import uuid

from django.core.validators import MaxValueValidator
from django.db import models
from django.db.models import Avg, Count, F, Sum
from django.db.models.functions import Coalesce
from django.urls import reverse
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _
from solo.models import SingletonModel


class Model(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created at"))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("updated at"))

    class Meta:
        abstract = True


class PaymentMethodQuerySet(models.QuerySet):
    def with_turnover(self):
        return self.annotate(
            turnover=Coalesce(
                Sum(
                    F("baskets__items__quantity")
                    * F("baskets__items__unit_price_cents"),
                ),
                0,
            ),
        )

    def with_sold(self):
        return self.annotate(sold=Count("baskets", distinct=True))


class PaymentMethodManager(models.Manager):
    def get_by_natural_key(self, name):
        return self.get(name=name)


class PaymentMethod(Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=_("name"))

    objects = PaymentMethodManager.from_queryset(PaymentMethodQuerySet)()

    class Meta:
        verbose_name = _("payment method")
        verbose_name_plural = _("payment methods")
        ordering = ("name",)

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.name,)


def default_product_display_order():
    last = Product.objects.last()
    if last is None:
        return 1
    return last.display_order + 1


class ProductCategory(Model):
    name = models.CharField(max_length=250, unique=True, verbose_name=_("name"))
    color_hue = models.PositiveIntegerField(
        validators=[MaxValueValidator(360)],
        verbose_name=_("color hue"),
        help_text=_("Color hue in degrees (0-360)"),
    )

    class Meta:
        verbose_name = _("product category")
        verbose_name_plural = _("product categories")

    def __str__(self):
        return self.name


class ProductQuerySet(models.QuerySet):
    def with_turnover(self):
        return self.annotate(
            turnover=Coalesce(
                Sum(F("basket_items__quantity") * F("basket_items__unit_price_cents")),
                0,
            ),
        )

    def with_sold(self):
        return self.annotate(sold=Coalesce(Sum("basket_items__quantity"), 0))

    def with_fixed_price(self):
        return self.exclude(unit_price_cents=0)

    def with_no_fixed_price(self):
        return self.filter(unit_price_cents=0)

    def with_category(self):
        return self.select_related("category")


class ProductManager(models.Manager):
    def get_by_natural_key(self, name):
        return self.get(name=name)


class Product(Model):
    name = models.CharField(max_length=250, unique=True, verbose_name=_("name"))
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.PROTECT,
        verbose_name=_("category"),
        null=False,
        blank=False,
    )
    unit_price_cents = models.PositiveIntegerField(
        verbose_name=_("unit price (cents)"),
        help_text=_(
            "Unit price in cents. Use zero to denote that the product has no fixed price.",
        ),
    )
    initials = models.CharField(
        max_length=10,
        verbose_name=_("initials"),
        blank=False,
        null=False,
    )
    display_order = models.PositiveIntegerField(
        default=default_product_display_order,
        verbose_name=_("display order"),
    )

    objects = ProductManager.from_queryset(ProductQuerySet)()

    class Meta:
        ordering = ["display_order", "name"]
        verbose_name = _("product")
        verbose_name_plural = _("products")

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.name,)

    @property
    def color_hue(self):
        return self.category.color_hue

    @property
    def has_fixed_price(self) -> bool:
        return self.unit_price_cents > 0


class BasketQuerySet(models.QuerySet):
    def with_articles_count(self) -> BasketQuerySet:
        return self.annotate(articles_count=Sum(F("items__quantity")))

    def priced(self) -> BasketQuerySet:
        return self.annotate(
            price=Coalesce(Sum(F("items__quantity") * F("items__unit_price_cents")), 0),
        )

    def average_basket(self) -> float:
        return self.priced().aggregate(avg=Avg("price"))["avg"]

    def by_date(self, date) -> BasketQuerySet:
        return self.filter(created_at__date=date)

    def turnover(self) -> int:
        return self.priced().aggregate(total=Sum("price"))["total"]


class Basket(Model):
    payment_method = models.ForeignKey(
        to=PaymentMethod,
        on_delete=models.PROTECT,
        related_name="baskets",
        null=False,
        blank=False,
        verbose_name=_("payment method"),
    )

    objects = BasketQuerySet.as_manager()

    class Meta:
        verbose_name = _("basket")
        verbose_name_plural = _("baskets")

    def __str__(self):
        return gettext("Basket #%(id)s") % {"id": self.id}

    def get_absolute_url(self):
        return reverse("purchase:update", args=(self.pk,))


class BasketItemQuerySet(models.QuerySet):
    def priced(self):
        return self.annotate(price=Coalesce(F("quantity") * F("unit_price_cents"), 0))


class BasketItem(Model):  # noqa: DJ008
    product = models.ForeignKey(
        to=Product,
        on_delete=models.PROTECT,
        related_name="basket_items",
        verbose_name=_("product"),
    )
    basket = models.ForeignKey(
        to=Basket,
        on_delete=models.CASCADE,
        related_name="items",
        verbose_name=_("basket"),
    )
    quantity = models.PositiveIntegerField(verbose_name=_("quantity"))
    unit_price_cents = models.PositiveIntegerField(
        verbose_name=_("unit price (cents)"),
        help_text=_("product's unit price in cents at the time of purchase"),
    )

    objects = BasketItemQuerySet.as_manager()

    class Meta:
        verbose_name = _("basket item")
        verbose_name_plural = _("basket items")


class Cache(SingletonModel):
    etag = models.UUIDField(default=uuid.uuid4)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return str(self.etag)

    def refresh(self):
        self.etag = uuid.uuid4()
        self.save()


def reports_etag(_request):
    return str(Cache.get_solo().etag)


def reports_last_modified(_request):
    return Cache.get_solo().last_modified

src/common/views.py
from django.shortcuts import redirect, render


def home(_request):
    return redirect("purchase:new")


def ping(request):
    return render(request, "common/ping.html", {})


def error_check(_request):
    msg = "Error check"
    raise ValueError(msg)

src/common/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Checkout</title>
        <link href="{% static "vendor/bootstrap-5.2.3-dist/css/bootstrap.min.css" %}"
              rel="stylesheet">
        {% include "common/favicon.html" %}
        <style>
            body {
                margin-bottom: 2em;
                touch-action: manipulation;
            }
        </style>
        <script defer src="{% static "vendor/fontawesome-6.3.0-free/brands.min.js" %}"></script>
        <script defer src="{% static "vendor/fontawesome-6.3.0-free/solid.min.js" %}"></script>
        <script defer src="{% static "vendor/fontawesome-6.3.0-free/fontawesome.min.js" %}"></script>

        {% block extrahead %}
        {% endblock %}
    </head>
    <body>
        <div class="container-fluid">
            {% include "common/navbar.html" %}
            {% include "common/messages.html" %}
            {% block content %}
            {% endblock %}
        </div>
        <script src="{% static "vendor/bootstrap-5.2.3-dist/js/bootstrap.bundle.min.js" %}"></script>
        {% block extrascript %}
        {% endblock %}
    </body>
</html>

src/common/templates/common/favicon.html
{% load static %}
<link rel="apple-touch-icon" sizes="180x180" href="{% static "icons/apple-touch-icon.png" %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static "icons/favicon-32x32.png" %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static "icons/favicon-16x16.png" %}">
<link rel="manifest" href="{% static "icons/site.webmanifest" %}">
<link rel="mask-icon" href="{% static "icons/safari-pinned-tab.svg" %}" color="#5bbad5">
<link rel="shortcut icon" href="{% static "icons/favicon.ico" %}">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="{% static "icons/browserconfig.xml" %}">
<meta name="theme-color" content="#ffffff">

src/common/templates/common/messages.html
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}

src/common/templates/common/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url "purchase:list" %}">Checkout</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                {% if perms.purchase.add_basket %}
                    <li class="nav-item">
                        <a href="{% url "purchase:new" %}" class="nav-link">{% translate "New basket" %}</a>
                    </li>
                {% endif %}
                {% if perms.purchase.view_basket %}
                    <li class="nav-item">
                        <a href="{% url "purchase:list" %}" class="nav-link">{% translate "Baskets" %}</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url "purchase:reports" %}" class="nav-link">{% translate "Reports" %}</a>
                    </li>
                {% endif %}
                {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "admin:index" %}">{% translate "Admin" %}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

src/common/templates/common/ping.html
{% extends "common/base.html" %}
{% block content %}
    <h1>Ping</h1>
    <h2>Versions</h2>
    <ul>
        <li>Build date: {{ build.date }}</li>
        <li>Commit: {{ build.commit }}</li>
        <li>Version: {{ build.describe }}</li>
    </ul>
{% endblock %}